EMAIL_ADDRESS = "suryakanna165@gmail.com"
PASSWORD = "Kanna7263"
PROXY_HOST = "172.31.2.4"
PROXY_PORT = 8080
baseLink = "https://www.imdb.com"
DATABASE_HOST="localhost"
DATABASE_USER="root"
DATABASE_PASSWORD="1234"
DATABASE_NAME="spoilers"
